PATTERNS = {
    "AWS Access Key": (r"\bAKIA[0-9A-Z]{16}\b", 9, "api_key"),
    "AWS Secret Key": (r"(?i)aws.{0,20}secret.{0,20}['\"][0-9a-zA-Z/+]{40}['\"]", 9, "api_secret"),
    "GitHub Token": (r"\bghp_[a-zA-Z0-9]{36}\b", 9, "api_token"),
    "GitHub OAuth": (r"\bgho_[a-zA-Z0-9]{36}\b", 8, "oauth_token"),
    "GitHub App Token": (r"\bghs_[a-zA-Z0-9]{36}\b", 8, "app_token"),
    "Slack Token": (r"\bxox[bpoa]-[0-9a-zA-Z\-]{10,48}\b", 8, "api_token"),
    "Stripe Secret Key": (r"\bsk_live_[0-9a-zA-Z]{24,}\b", 9, "api_secret"),
    "Stripe Publishable Key": (r"\bpk_live_[0-9a-zA-Z]{24,}\b", 5, "api_key"),
    "Twilio Account SID": (r"\bAC[a-zA-Z0-9]{32}\b", 7, "account_id"),
    "Twilio Auth Token": (r"\b[a-f0-9]{32}\b", 3, "api_secret"),
    "Google API Key": (r"\bAIza[0-9A-Za-z\-_]{35}\b", 8, "api_key"),
    "Google OAuth": (r"\b[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com\b", 7, "oauth_client"),
    "Private Key": (r"-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----", 10, "private_key"),
    "JWT Token": (r"\beyJ[a-zA-Z0-9_\-]+\.[a-zA-Z0-9_\-]+\.[a-zA-Z0-9_\-]+\b", 7, "jwt"),
    "Bearer Token": (r"(?i)bearer\s+[a-zA-Z0-9_\-\.=]{20,}", 6, "bearer_token"),
    "Basic Auth": (r"(?i)basic\s+[a-zA-Z0-9+/]{20,}={0,2}\b", 6, "basic_auth"),
    "Telegram Bot Token": (r"\b[0-9]{8,10}:[a-zA-Z0-9_\-]{35}\b", 8, "bot_token"),
    "SendGrid API Key": (r"\bSG\.[a-zA-Z0-9_\-]{22}\.[a-zA-Z0-9_\-]{43}\b", 9, "api_key"),
    "Mailgun API Key": (r"\bkey-[a-zA-Z0-9]{32}\b", 7, "api_key"),
    "HubSpot API Key": (r"\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b", 3, "api_key"),
    "Generic API Key": (r"(?i)api[_\-\s]?key\s*[=:]\s*['\"]?([a-zA-Z0-9_\-\.]{20,})['\"]?", 5, "api_key"),
    "Generic Secret": (r"(?i)(?:secret|password|passwd|pwd)\s*[=:]\s*['\"]([^'\"]{8,})['\"]", 5, "credential"),
    "Generic Token": (r"(?i)token\s*[=:]\s*['\"]([a-zA-Z0-9_\-\.]{16,})['\"]", 4, "api_token"),
    "Connection String": (
        r"(?i)(postgres|mysql|mongodb|redis|amqp)://[^\s'\"]+:[^\s'\"]+@[^\s'\"]+",
        8,
        "db_credential",
    ),
    "Private IP in code": (
        r"(?i)(?:host|server|endpoint)\s*[=:]\s*['\"]?(192\.168\.|10\.|172\.(?:1[6-9]|2[0-9]|3[01])\.)",
        2,
        "internal_endpoint",
    ),
}

CONTEXT_KEYWORDS = [
    "api_key",
    "apikey",
    "secret",
    "password",
    "passwd",
    "pwd",
    "token",
    "auth",
    "credential",
    "private_key",
    "access_key",
    "client_secret",
    "app_secret",
    "api_secret",
    "database_url",
    "connection_string",
]

IGNORE_PATTERNS = [
    r"example",
    r"test",
    r"fake",
    r"dummy",
    r"placeholder",
    r"xxxx",
    r"1234",
    r"your[_\-]?key",
    r"<[^>]+>",
    r"\*{4,}",
    r"TODO",
    r"FIXME",
]

HASH_PATTERNS = [
    r"^[a-f0-9]{32}$",
    r"^[a-f0-9]{40}$",
    r"^[a-f0-9]{64}$",
]

SKIP_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".svg",
    ".ico",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".mp4",
    ".mp3",
    ".zip",
    ".tar",
    ".gz",
    ".pdf",
    ".lock",
    ".sum",
    ".exe",
    ".dll",
    ".so",
    ".bin",
}

SKIP_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    ".idea",
    ".vscode",
    "vendor",
    "target",
    "out",
}

HIGH_ENTROPY_FILE_TYPES = {".env", ".cfg", ".conf", ".ini", ".yaml", ".yml", ".json", ".toml"}

SINK_NAMES = {
    r"\brequests\.(get|post|put|patch|delete|head)\b": "HTTP request",
    r"\burllib\.request\.": "HTTP request",
    r"\bhttpx\.(get|post|put|patch|delete)\b": "HTTP request",
    r"\baiohttp\.": "HTTP request",
    r"\bsmtplib\.": "Email sending",
    r"\blogging\.(info|debug|warning|error|critical)\b": "Logging",
    r"\bprint\s*\(": "Console output",
    r"\bopen\s*\(": "File write",
    r"\bsubprocess\.(run|call|Popen|check_output)\b": "Shell execution",
    r"\bos\.system\s*\(": "Shell execution",
    r"\bsocket\.": "Raw socket",
    r"\bparamiko\.": "SSH connection",
    r"\bpysftp\.": "SFTP connection",
    r"\bboto3\.": "AWS SDK call",
    r"\bpymongo\.": "MongoDB query",
    r"\bpsycopg2\.": "PostgreSQL query",
    r"\bsqlalchemy\.": "Database query",
    r"\bsequelize\.": "Database query",
    r"\bexec\s*\(": "Dynamic code execution",
}
